name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.x'
        environment-file: environment.yml
        use-only-tar-bz2: true # Use only .tar.bz2 packages to reduce bandwidth usage.
    - name: Install dependencies
      run: |
        conda env update --name myenv --file environment.yml
    - name: Lint with flake8
      run: |
        conda run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: smcpp-pipeline
      run: |
        conda install smcpp-pipeline
    - name: Build Conda package
      run: |
        conda install conda-build
        conda build .
    # Assuming you have an Anaconda account and have generated an API token
    - name: Upload Conda package to Anaconda Cloud
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
      run: |
        conda install anaconda-client
        anaconda upload --user Devashish13 $(conda build . --output)
